services:
  db:
    image: postgres:14-alpine
    container_name: postgres_topcon
    restart: always
    environment:
      POSTGRES_DB: prova_topcon
      POSTGRES_USER: topcon
      POSTGRES_PASSWORD: prova
    ports:
      - "5432:5432"
    volumes:
      # Mapeamento da pasta f√≠sica do Windows para a pasta de dados do Postgres
      - "D:/prova topcon/BD:/var/lib/postgresql/data"